app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('posts/', include('posts.urls')),
]
urlpatterns += static(
    # URL앞부분이 /media/이면
    prefix='/media/',
    # document_root위치에서 나머지 path에 해당하는 파일을 리턴
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from . import views


app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

app/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # /posts/
    path('', views.post_list, name='post-list'),

    # /posts/3/like/
    path('<int:pk>/like/', views.post_like, name='post-like'),

    # /posts/create/
    path('create/', views.post_create, name='post-create'),

    # /posts/3/comments/create/
    path('<int:post_pk>/comments/create/', views.comment_create, name='comment-create'),
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    사용자모델로 쓰입니다.
    """
    img_profile = models.ImageField('프로필이미지', blank=True, upload_to='users/')
    name = models.CharField('이름', max_length=100, null=True)

app/posts/models.py
from django.db import models

from members.models import User


class Post(models.Model):
    """
    인스타그램의 포스트
    """
    # 기본값 post_set
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    # 'PostLike를 통한 Many-to-Many구현'
    like_users = models.ManyToManyField(User, through='PostLike', related_name='like_post_set')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        author = self.author
        content = self.content
        return f'{author}, {content}'


class PostImage(models.Model):
    """
    각 포스트의 사진
    pip install pillow
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts/images')


class PostComment(models.Model):
    """
    각 포스트의 댓글 (Many-to-one)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()


class PostLike(models.Model):
    """
    사용자가 좋아요 누른 Post정보를 저장
    Many-to-many필드의 중간모델(Intermediate Model)을 거쳐 사용
        언제 생성되었는지를 Extra field로 저장! (created)
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

app/members/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError
from django.http import HttpResponse


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '아이디',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호',
            }
        )
    )

    def clean(self):
        # Form.clean에서는 cleaned_data에 접근 가능
        # cleaned_data에는 이 Form이 가진 모든 Field들에서 리턴된 데이터가 key: value로 들어있음
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if not user:
            raise ValidationError('username 또는 password가 올바르지 않습니다.')
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        login(request, user)


class SignupForm(forms.Form):
    def save(self):
        pass

app/posts/forms.py
from django import forms


class PostCreateForm(forms.Form):
    """
    이 Form에 들어갈 입력요소
        Image(File)
        Text
    """
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
            }
        )
    )
    text = forms.CharField()


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        max_length=10,
        widget=forms.Textarea()
    )

    def save(self, post, author):
        return post.postcomment_set.create(
            author=author,
            content=self.cleaned_data['content'],
        )

app/config/views.py
from django.shortcuts import render, redirect


def index(request):
    if request.user.is_authenticated:
        return redirect('posts:post-list')
    return render(request, 'index.html')

app/members/views.py
from django.contrib.auth import login, logout, get_user_model
from django.http import HttpResponse
from django.shortcuts import redirect, render

from members.forms import LoginForm
from members.models import User

User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            form.login(request)
            return redirect('posts:post-list')
    else:
        form = LoginForm()

    context = {
        'form': form,
    }
    return render(request, 'members/login.html', context)


def signup_view(request):
    email = request.POST['email']
    username = request.POST['username']
    name = request.POST['name']
    password = request.POST['password']

    if User.objects.filter(username=username).exists():
        return HttpResponse('이미 사용중인 username입니다')
    if User.objects.filter(email=email).exists():
        return HttpResponse('이미 사용중인 email입니다')

    user = User.objects.create_user(
        password=password,
        username=username,
        email=email,
        name=name,
    )
    login(request, user)
    return redirect('posts:post-list')


def logout_view(request):
    logout(request)
    return redirect('members:login')

app/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, PostLike, PostImage
from .forms import PostCreateForm, CommentCreateForm


def post_list(request):
    posts = Post.objects.order_by('-pk')
    comment_form = CommentCreateForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/post-list.html', context)


def post_like(request, pk):
    """
    pk가 pk인 Post와 (변수명 post사용)
    request.user로 전달되는 User (변수명 user사용)에 대해
    1. PostLike(post=post, user=user)인 PostLike객체가 존재하는지 확인한다
    2-1. 만약 해당 객체가 이미 있다면, 삭제한다
    2-2. 만약 해당 객체가 없다면 새로 만든다
    3. 완료 후 posts:post-list로 redirect한다
    URL: /posts/<pk>/like/
    """
    post = Post.objects.get(pk=pk)
    user = request.user
    print('post:', post)
    print('user:', user)

    post_like_qs = PostLike.objects.filter(post=post, user=user)
    # user, post에 해당하는 PostLike가 있는 경우
    if post_like_qs.exists():
        # 삭제
        post_like_qs.delete()
    # 없는 경우
    else:
        # 만든다
        PostLike.objects.create(post=post, user=user)

    return redirect('posts:post-list')


def post_create(request):
    """
    URL:        /posts/create/, name='post-create'
    Template:   /posts/post-create.html
    forms.PostCreateForm을 사용
    """
    if request.method == 'POST':
        text = request.POST['text']
        images = request.FILES.getlist('image')

        post = Post.objects.create(
            author=request.user,
            content=text
        )
        for image in images:
            post.postimage_set.create(image=image)

        return redirect('posts:post-list')
    else:
        form = PostCreateForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post-create.html', context)


def comment_create(request, post_pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=post_pk)
        # Form인스턴스를 만드는데, data에 request.POST로 전달된 dict를 입력
        form = CommentCreateForm(data=request.POST)
        # Form인스턴스 생성시, 주어진 데이터가
        # 해당 Form이 가진 Field들에 적절한 데이터인지 검증
        if form.is_valid():
            form.save(post=post, author=request.user)
        return redirect('posts:post-list')

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <title>Instagram</title>
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrap">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
        <div class="card text-center p-4">
            <div>{{ request.user }}</div>
            <div>{{ request.user.is_authenticated }}</div>

            <h1>Instagram</h1>
            <p class="text-secondary">친구들의 사진과 동영상을 보려면 가입하세요</p>
            <button class="btn btn-primary btn-block">Facebook으로 로그인</button>
            <hr>
            <form action="{% url 'members:signup' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="이메일 주소">
                </div>
                <div class="form-group">
                    <input name="name" type="text" class="form-control" placeholder="성명">
                </div>
                <div class="form-group">
                    <input name="username" type="text" class="form-control" placeholder="사용자 이름">
                </div>
                <div class="form-group">
                    <input name="password" type="password" class="form-control" placeholder="비밀번호">
                </div>
                <button type="submit" class="btn btn-primary btn-block">가입</button>
            </form>
            <p class="text-secondary">가입하면 Instagram의 약관 데이터 정책 및 쿠키 정책에 동의하게 됩니다</p>
        </div>

        <div class="card text-center p-4 mt-3 mb-3">
            <span>계정이 있으신가요?</span>
            <a href="{% url 'members:login' %}">로그인</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/members/login.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mr-auto ml-auto mt-3
                    col-lg-4
                    col-md-6
                    col-sm-8
                    col-10">
            <div class="card text-center p-4">
                <h1>Instagram</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
                    {% if form.non_field_errors %}
                    <ul class="list-unstyled text-danger">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <button class="btn btn-primary btn-block">로그인</button>
                </form>
                <hr>
                <button class="btn btn-block btn-outline-primary mb-3">Facebook으로 로그인</button>
                <a href="">비밀번호를 잊으셨나요?</a>
            </div>

            <div class="card text-center p-4 mt-3 mb-3">
                <span>계정이 없으신가요?</span>
                <a href="{% url 'index' %}">가입하기</a>
            </div>
        </div>
    </div>
{% endblock %} 

app/templates/posts/post-create.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">작성</button>
</form>
</body>
</html>

app/templates/posts/post-list.html
{% extends 'base.html' %}

{% block content %}
<div>User: {{ request.user }}</div>
<div>Authenticated: {{ request.user.is_authenticated }}</div>
<div>
    <!--
    로그아웃버튼 (a태그로 구현)
    이 버튼은 사용자가 로그인되어있을때만 보여주도록 한다
    -->
    <a href="{% url 'members:logout' %}">로그아웃</a>
</div>
<div>
    <a href="{% url 'posts:post-create' %}">포스트 추가</a>
</div>
{% for post in posts %}
<div>작성자: {{ post.author }}</div>
<div>작성일시: {{ post.created }}</div>
<div>글내용: {{ post.content }}</div>
<div>
    {% for post_image in post.postimage_set.all %}
    <img src="{{ post_image.image.url }}" alt="" style="max-width: 200px;">
    {% endfor %}
</div>
<form action="{% url 'posts:post-like' pk=post.pk %}" method="POST">
    {% csrf_token %}
    {% if post in user.like_post_set.all %}
    <button class="btn btn-primary" type="submit">좋아요 취소</button>
    {% else %}
    <button class="btn btn-outline-primary" type="submit">좋아요</button>
    {% endif %}
</form>
<div>
    <ul>
        {% for comment in post.postcomment_set.all %}
        <li>
            <b>{{ comment.author.name }}</b>
            <span>{{ comment.content }}</span>
        </li>
        {% endfor %}
    </ul>
    <div>
        <!-- Comment를 작성하는 Form -->
        <form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <button type="submit">작성</button>
        </form>
    </div>
</div>
<hr>
{% endfor %}
{% endblock %}